table customer_master
	lineageTag: be96931c-4914-44c4-bfa3-b00899d382e3

	column Customer_ID
		dataType: string
		lineageTag: 6d3b0ef2-9d46-407f-aa77-971b578572bc
		summarizeBy: none
		sourceColumn: Customer_ID

		annotation SummarizationSetBy = Automatic

	column Customer_Name
		dataType: string
		lineageTag: 3f341efc-a3bd-42e3-bf9e-eba1a8dee54d
		summarizeBy: none
		sourceColumn: Customer_Name

		annotation SummarizationSetBy = Automatic

	column Industry
		dataType: string
		lineageTag: f2df98ac-7814-4608-bf42-595a8d7c9a59
		summarizeBy: none
		sourceColumn: Industry

		annotation SummarizationSetBy = Automatic

	column Market_Segment
		dataType: string
		lineageTag: b372b23c-7f78-4d14-a407-d4776719393f
		summarizeBy: none
		sourceColumn: Market_Segment

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: ec012bb9-980e-4773-b114-73083dac61ef
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: ee4105c5-9885-4b9a-bacc-e2d237d1394a
		summarizeBy: none
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: 7271578c-2df2-4235-be88-e479f8d1341e
		summarizeBy: none
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition customer_master = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Mohamed Samy\Downloads\archive (11)\customer_master.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer_ID", type text}, {"Customer_Name", type text}, {"Industry", type text}, {"Market_Segment", type text}, {"Country", type text}, {"City", type text}, {"Latitude", type number}, {"Longitude", type number}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"Customer_ID"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Duplicates",{"Country"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

