table product_master
	lineageTag: da9207a0-21fb-44f2-9c18-d3ae8cf97072

	column Product_ID
		dataType: string
		lineageTag: cbc03852-3d62-48d8-8a66-e7f1e3480028
		summarizeBy: none
		sourceColumn: Product_ID

		annotation SummarizationSetBy = Automatic

	column SKU
		dataType: string
		lineageTag: ded85208-cd87-45ac-acae-cefd2de06f60
		summarizeBy: none
		sourceColumn: SKU

		annotation SummarizationSetBy = Automatic

	column Product_Name
		dataType: string
		lineageTag: dc1281ba-d916-4cc3-8ce4-1f0d64370044
		summarizeBy: none
		sourceColumn: Product_Name

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 41859f3e-080c-4c88-adb9-6b090e019166
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		lineageTag: c06e2510-8785-499e-94cf-e763f9e534f2
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column Unit_Cost
		dataType: double
		lineageTag: 774d7de0-1f2a-4f5d-966c-0f0ced971937
		summarizeBy: sum
		sourceColumn: Unit_Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Standard_Price
		dataType: double
		lineageTag: 23b93351-8eef-41c7-8635-de11225ff53d
		summarizeBy: sum
		sourceColumn: Standard_Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Launch_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a87ecb6e-b159-4ae9-86c1-b5caa4f6d2e8
		summarizeBy: none
		sourceColumn: Launch_Date

		variation Variation
			isDefault
			relationship: 956cb80b-be7b-4156-99b1-54d9d723a92f
			defaultHierarchy: LocalDateTable_545b1eb6-8e99-46a5-8186-ea021bbeb324.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column profit
		dataType: double
		lineageTag: d508e273-cdc2-47c9-a21a-d5263efade37
		summarizeBy: sum
		sourceColumn: profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition product_master = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Mohamed Samy\Downloads\archive (11)\product_master.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Product_ID", type text}, {"SKU", type text}, {"Product_Name", type text}, {"Category", type text}, {"Subcategory", type text}, {"Unit", type text}, {"Unit_Cost", type number}, {"Standard_Price", type number}, {"Launch_Date", type date}, {"Discontinuation_Date", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Unit", "Discontinuation_Date"}),
				    #"Inserted Subtraction" = Table.AddColumn(#"Removed Columns", "Subtraction", each [Standard_Price] - [Unit_Cost], type number),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Subtraction",{{"Subtraction", "profit"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

