table sales_orders
	lineageTag: 637b135e-a950-47a5-be5c-2ee5167bfacf

	column Order_id
		dataType: string
		lineageTag: 95f40da6-a15c-4db7-aece-7f7b69518bf7
		summarizeBy: none
		sourceColumn: Order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: c9433404-d45b-47ba-88e2-f0c3cd80a0b8
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 5b214ec6-8349-406c-ac91-70152ac7bccf
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: bfbf2743-3af6-41f1-8b58-4085d218d42f
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Order_status
		dataType: string
		lineageTag: 06fb83a8-884e-402e-a998-8e3bdc362f64
		summarizeBy: none
		sourceColumn: Order_status

		annotation SummarizationSetBy = Automatic

	column Order_Quantity
		dataType: double
		lineageTag: 78c0a565-65a8-43c1-baa5-0cb6a1e88278
		summarizeBy: sum
		sourceColumn: Order_Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Unit_price
		dataType: double
		lineageTag: ab8ecda6-dd8b-48d0-8111-c068908e501f
		summarizeBy: sum
		sourceColumn: Unit_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discount
		dataType: double
		lineageTag: 996dd3b0-e3ac-4529-b21e-4f56df0502f4
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Shipping_Mode
		dataType: string
		lineageTag: ff11bcee-2189-4591-931c-c9ef50535c38
		summarizeBy: none
		sourceColumn: Shipping_Mode

		annotation SummarizationSetBy = Automatic

	column Shipping_Carrier
		dataType: string
		lineageTag: 0105f87d-5343-4d3d-bb1c-33353374e70e
		summarizeBy: none
		sourceColumn: Shipping_Carrier

		annotation SummarizationSetBy = Automatic

	column Shipping_date_scheduled
		dataType: dateTime
		formatString: Long Date
		lineageTag: e6a33882-aba0-433c-9ded-7b0c59be55ac
		summarizeBy: none
		sourceColumn: Shipping_date_scheduled

		variation Variation
			isDefault
			relationship: f980a0b4-8b55-4b8d-b06f-c0312ee807fd
			defaultHierarchy: LocalDateTable_c0114f4f-3370-4495-bcdb-2da660c64b27.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Shipping_Date_Actual
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3aa66980-f412-4535-9af4-d14e7806afd9
		summarizeBy: none
		sourceColumn: Shipping_Date_Actual

		variation Variation
			isDefault
			relationship: c513439c-46e1-4da2-9da1-dc78b7b2dd0e
			defaultHierarchy: LocalDateTable_7a233fd8-e63b-44c9-86db-8de6f4c7bc04.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Delivery_status
		dataType: string
		lineageTag: f4bf5630-f05c-4e9b-9822-313bedb91e58
		summarizeBy: none
		sourceColumn: Delivery_status

		annotation SummarizationSetBy = Automatic

	column Late_Delivery_Risk_Flag
		dataType: double
		lineageTag: 1a41cd04-a081-4bc5-991d-95ca61f264b0
		summarizeBy: sum
		sourceColumn: Late_Delivery_Risk_Flag

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Vate_Rate
		dataType: double
		lineageTag: e5396c73-7a4f-4c49-894b-4f57ad424a8f
		summarizeBy: sum
		sourceColumn: Vate_Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COGS
		dataType: double
		lineageTag: 6ecd370b-ed47-4824-807d-487c310a3cac
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Unite_Price_Effective
		dataType: double
		lineageTag: e0165ca6-ced2-48f1-b5ce-d1e4f0bbaca9
		summarizeBy: sum
		sourceColumn: Unite_Price_Effective

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Order_Total
		dataType: double
		lineageTag: baf869fc-226e-4a7e-a265-47c0a7b4122d
		summarizeBy: sum
		sourceColumn: Order_Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Vat_Amount
		dataType: double
		lineageTag: a08478fc-24fe-458d-885b-a692c782080d
		summarizeBy: sum
		sourceColumn: Vat_Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit_Per_Order
		dataType: double
		lineageTag: b9ab7caa-d37e-4cf7-8dff-cec86803300f
		summarizeBy: sum
		sourceColumn: Profit_Per_Order

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Shipping day'
		dataType: int64
		formatString: 0
		lineageTag: 16458059-267a-4798-b71e-ebf7d00412e1
		summarizeBy: sum
		sourceColumn: Shipping day

		annotation SummarizationSetBy = Automatic

	partition sales_orders = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Mohamed Samy\Downloads\archive (11)\sales_orders.csv"),[Delimiter=",", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Order_id"}, {"Column2", "customer_id"}, {"Column3", "product_id"}, {"Column4", "order_date"}, {"Column5", "Order_status"}, {"Column6", "Order+Quantity"}, {"Column7", "Unit_price"}, {"Column8", "Discount"}, {"Column9", "Shipping_Mode"}, {"Column10", "Shipping_Carrier"}, {"Column11", "Shipping_date_scheduled"}, {"Column12", "Shippinf_Date_Actual"}, {"Column13", "Delivery_status"}, {"Column14", "Late_Delivery_Risk_Flag"}, {"Column15", "Vate_Rate"}, {"Column16", "COGS"}, {"Column17", "Unite_Price_Effective"}, {"Column18", "Order_Total"}, {"Column19", "Vat_Amount"}, {"Column20", "Profit_Per_Order"}}),
				    #"Removed Top Rows" = Table.Skip(#"Renamed Columns",2),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Top Rows",{{"Shippinf_Date_Actual", "Shipping_Date_Actual"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Order_Total", type number}, {"Unite_Price_Effective", type number}, {"COGS", type number}, {"Vat_Amount", type number}, {"Profit_Per_Order", type number}, {"Vate_Rate", type number}, {"Late_Delivery_Risk_Flag", type number}, {"Shipping_Date_Actual", type date}, {"Shipping_date_scheduled", type date}, {"Discount", type number}, {"Unit_price", type number}, {"Order+Quantity", type number}, {"order_date", type date}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type1",{{"Order+Quantity", "Order_Quantity"}}),
				    #"Inserted Date Subtraction" = Table.AddColumn(#"Renamed Columns2", "Subtraction", each Duration.Days([Shipping_Date_Actual] - [Shipping_date_scheduled]), Int64.Type),
				    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Date Subtraction",{{"Subtraction", "Shipping day"}})
				in
				    #"Renamed Columns3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

