table supplier_master
	lineageTag: 09a9a2c8-3627-4e46-a66a-d4afeb94ea9b

	column Supplier_ID
		dataType: string
		lineageTag: edf17043-45be-43a7-94d5-bff8e4ba3d78
		summarizeBy: none
		sourceColumn: Supplier_ID

		annotation SummarizationSetBy = Automatic

	column Supplier_Name
		dataType: string
		lineageTag: 81399615-5d39-402e-95c1-f01df05bb35a
		summarizeBy: none
		sourceColumn: Supplier_Name

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: fb8d2414-fa80-46b8-a3fd-cdd357c80afb
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: ab7f83ea-96f9-483c-8864-705d3acdb658
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column On_Time_Delivery_Rate
		dataType: double
		lineageTag: 8024e7a7-c98e-4e46-8c99-e366b248c330
		summarizeBy: none
		sourceColumn: On_Time_Delivery_Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Certification_Level
		dataType: string
		lineageTag: 565e5503-52c8-45d4-96dc-aab5ea996339
		summarizeBy: none
		sourceColumn: Certification_Level

		annotation SummarizationSetBy = Automatic

	column Preferred_Supplier_Flag
		dataType: int64
		formatString: 0
		lineageTag: 0c19686f-b0fc-4efa-8ab0-0e1325702b04
		summarizeBy: none
		sourceColumn: Preferred_Supplier_Flag

		annotation SummarizationSetBy = Automatic

	partition supplier_master = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Mohamed Samy\Downloads\archive (11)\supplier_master.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Supplier_ID", type text}, {"Supplier_Name", type text}, {"Country", type text}, {"Region", type text}, {"On_Time_Delivery_Rate", type number}, {"Certification_Level", type text}, {"Preferred_Supplier_Flag", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Certification_Level] <> "None")),
				    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows", {"Supplier_ID"}),
				    #"Trimmed Text" = Table.TransformColumns(#"Removed Duplicates",{{"Supplier_ID", Text.Trim, type text}}),
				    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"Supplier_ID", Text.Clean, type text}})
				in
				    #"Cleaned Text"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

